name: Discord

on:
  push:
  pull_request:
  issues:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Github
        run: |
          PAYLOAD="{
            \"content\": \"$GITHUB_EVENT_NAME\",
            \"embeds\": [{
              \"title\": \"${GITHUB_REPOSITORY}\",
              \"description\": \"${GITHUB_ACTOR}: $GITHUB_EVENT_NAME\",
              \"color\": 0
            }]
          }"
          curl -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               ${{ secrets.DISCORD_WEBHOOK }}
